### ISSUE TITLE
Can't View Entry after going to Main Form

### ISSUE THREAD

**Issue by MattRossi** [shilongdai/vsDiaryWriter#1]
I have made a Journal, added a title, and entered some HTML code into the source tab, reviewed the code in the normal tab, and pressed the save button at the bottom. When I go back to look at it after going to the main form, there is nothing in the text box. I have attached pictures to show you what I mean. (I understand that not all of the page elements are not going to work, but the text is still there.)
![image1](https://cloud.githubusercontent.com/assets/12902926/14078147/5472c814-f4c1-11e5-8d8d-4b579f65df41.PNG)
![image2](https://cloud.githubusercontent.com/assets/12902926/14078149/57e4a1e8-f4c1-11e5-9dea-b2b159fe1fdb.PNG)
![image3](https://cloud.githubusercontent.com/assets/12902926/14078150/596b63bc-f4c1-11e5-89bc-1d0ed73ad243.PNG)
![save4](https://cloud.githubusercontent.com/assets/12902926/14078151/5af0432e-f4c1-11e5-95a6-46d61562a714.PNG)
Awesome program so far!

**Comment by shilongdai** [comment]
Since this is a JavaScript HTML editor, it works properly with a regular browser. However, this application only uses an embedded browser so right now I can't do anything about it other than to disable source editing

**Comment by shilongdai** [comment]
The problem is not with the editor but with the Max allowed characters in the database table colume

**Comment by shilongdai** [comment]
I will change the database column size and that should fix the problem

**Comment by shilongdai** [comment]
Lol, the average web page size is 2 MB now, I guess I am going to make the DB column at lease 5 mb

**Comment by MattRossi** [comment]
wow

**Comment by shilongdai** [comment]
The size problem is fixed. However, for the source editing to work, HTML must be self contained. Meaning that there can be no external script, css, or any other files of this kind. Otherwise, the editor won't save properly. Also, since this is not an actual webpage, no some tags will be discarded automatically
![works1](https://cloud.githubusercontent.com/assets/10383669/14096098/05c0b7c6-f534-11e5-8d27-8a548feb6bfd.png)

**Comment by shilongdai** [comment]
Copied an entire web page of Romeo and Juliet into the editor and it works
![works2](https://cloud.githubusercontent.com/assets/10383669/14096168/89640c9a-f534-11e5-9676-9fe3694487b2.png)
